import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {makeModel,disposeModel} from '../src/workbench/geometry.mjs';
import {referenceKumpf,cfg,calibratedCycle,vesselPose} from '../src/workbench/calibration.mjs';
test('four holes are open geometric passages and the retained base fits the groove',()=>{
 const m=referenceKumpf({nails:false}),staves=m.children.filter(x=>x.userData.staveIndex!==undefined);assert.equal(staves.length,12);assert.equal(staves.filter(x=>x.userData.drilled).length,2);
 for(const d of cfg.reference.holeOffsets){const hits=new T.Raycaster(new T.Vector3(-.4,0,.3-d),new T.Vector3(1,0,0),0,.8).intersectObjects(staves);assert.equal(hits.length,0,'a nail centerline must pass through both opposed holes without wood');const blocked=new T.Raycaster(new T.Vector3(-.4,0,.3-d+.04),new T.Vector3(1,0,0),0,.8).intersectObjects(staves);assert.ok(blocked.length>=4,'adjacent solid stave regions must remain present')}
 const base=m.children.find(x=>x.userData.family==='COMP-KUMPF-BASE');base.geometry.computeBoundingBox();assert.ok(base.geometry.boundingBox.max.z<-.3+cfg.reference.baseOffset+cfg.reference.grooveWidth/2);disposeModel(m)
});
test('truth exports exclude synthetic site, water, exact nail paths and all-vessel inventory',()=>{const m=makeModel('A',0,{modelMode:'truth'});assert.ok(!m.children.some(x=>x.userData.stationary||x.userData.nailPath));assert.equal(new Set(m.children.filter(x=>x.userData.family==='COMP-KUEMPFE').map(x=>x.userData.slot)).size,3);assert.equal(m.userData.truthConstraints.exactNailPaths,null);for(const x of m.children)assert.notEqual(x.userData.status,'measured');disposeModel(m)});
test('cycle uses calibrated mouth pose, conserves free-surface capacity and never fills above a dry river',()=>{
 for(let i=0;i<180;i++){const a=i*Math.PI/90,s=calibratedCycle(a),pose=vesselPose(a),mouth=new T.Vector3(0,0,.3).applyQuaternion(pose.quaternion).add(pose.position);assert.ok(mouth.distanceTo(new T.Vector3(...s.mouth))<1e-8);assert.ok(s.fill>=0&&s.fill<=1);assert.equal(calibratedCycle(a,{waterLevel:-10}).fill,0);assert.equal(calibratedCycle(a+Math.PI*2).state,s.state)}
 const states=Array.from({length:180},(_,i)=>calibratedCycle(i*Math.PI/90));assert.ok(states.some(x=>x.immersed&&x.fill>0));assert.ok(states.some(x=>x.inTrough));assert.ok(states.some(x=>x.discharging&&!x.inTrough),'losses must not be teleported into the trough');
});
test('corrected board plane has tangent normal and remains perpendicular to wheel plane',()=>{const m=makeModel(),pad=m.children.find(x=>x.userData.family==='COMP-PADDLES'),a=pad.userData.phase;const n=new T.Vector3(0,Math.cos(a),Math.sin(a));assert.equal(n.dot(new T.Vector3(1,0,0)),0);const v=pad.geometry.attributes.position;let lo=Infinity,hi=-Infinity;for(let i=0;i<v.count;i++){let t=new T.Vector3().fromBufferAttribute(v,i).dot(n);lo=Math.min(lo,t);hi=Math.max(hi,t)}assert.ok(Math.abs(hi-lo-cfg.production.paddleThickness)<1e-5);disposeModel(m)});
