import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {vesselState,solveRegistration} from '../src/workbench/mechanics.mjs';
const source=[[0,0,0],[1,0,0],[0,1,0]],target=[[2,3,4],[4,3,4],[2,5,4]],axisSource=[[0,0,0],[1,0,0]],axisTarget=[[2,3,4],[4,3,4]],control={source:[[0,0,1],[0,1,1]],measured:2,tolerance:.005};
test('no water can be lifted when the wheel never enters water',()=>{for(let a=0;a<Math.PI*2;a+=.1){const s=vesselState(a,{waterLevel:-2.3});assert.equal(s.fill,0);assert.equal(s.discharging,false)}});
test('phase follows positive-X rigid rotation and holding/discharge mouth pose',()=>{for(const a of[0,1,3,4,5.95]){const s=vesselState(a),p=new T.Vector3(0,0,2.25).applyAxisAngle(new T.Vector3(1,0,0),a);assert.ok(Math.abs(s.y-p.y)<1e-9);assert.ok(Math.abs(s.z-p.z)<1e-9)}assert.ok(vesselState(4.7).y>0);assert.ok(vesselState(4.7).mouthDirection[2]>.8);assert.ok(vesselState(6.1).mouthDirection[2]<0);assert.ok(vesselState(6.1).discharging);assert.equal(vesselState(.2).fill,0);assert.throws(()=>vesselState(NaN))});
test('registration validates known similarity, residuals, axis position and independent metric control',()=>{let r=solveRegistration(source,target,axisSource,axisTarget,control);assert.equal(r.passed,true);assert.equal(r.scale,2);assert.ok(r.rms<1e-9);assert.equal(r.adoption,'review-required');assert.equal(solveRegistration(source,target,axisSource,[[2,3.1,4],[4,3.1,4]],control).passed,false);assert.equal(solveRegistration(source,target,axisSource,axisTarget,{...control,measured:3}).passed,false);assert.equal(solveRegistration(source,[[2,3,4],[4,3,4],[2,5.02,4]],axisSource,axisTarget,control).passed,false)});
test('registration rejects invalid, infinite and degenerate datum/axis/control inputs',()=>{for(const bad of[null,[],[[0,0,0],[1,0,0],[2,0,0]],[[0,0,0],[1,0,0],[0,Infinity,0]]])assert.throws(()=>solveRegistration(bad,target,axisSource,axisTarget,control));assert.throws(()=>solveRegistration(source,target,[[0,0,0],[0,0,0]],axisTarget,control));assert.throws(()=>solveRegistration(source,target,axisSource,axisTarget,{...control,measured:NaN}));assert.throws(()=>solveRegistration(source,target,axisSource,axisTarget,{...control,source:[[0,0,0],[0,0,0]]}));});

test('water mouth faces the outboard trough at discharge and retains water while lifting',()=>{for(let a=5.9;a<6.2;a+=.05){const s=vesselState(a);assert.ok(s.mouthDirection[0]<0,'mouth must point toward trough on negative X');assert.ok(s.discharging)}assert.ok(vesselState(4.7).mouthDirection[2]>.8)});
