import {db,context} from './data.js';
import {config} from './geometry.mjs';
import {SCHEMA,openStore,readStore,writeStore,validateRecord,mergeImport} from './records.js';
import {createViewer} from './viewer.js';
const $=id=>document.getElementById(id),form=$('capture-form'),base=$('workbench').dataset.base;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={measurement:'Messung',observation:'Beobachtung',identification:'Identifikation','expert-narrative':'Expertenaussage',risk:'Risiko'};
let state={schema:SCHEMA,records:[],selection:'COMP-SHAFT',slot:null,draft:null,viewer:{}},store=null,viewer=null,step=1,media=[],queue=Promise.resolve(),ready=false;
const field=n=>form.elements.namedItem(n);
function snapshot(){return structuredClone({...state,draft:{values:formValues(),media,step,component_id:state.selection,slot:state.slot}})}
function formValues(){const v=Object.fromEntries(new FormData(form));v.unknown=field('unknown').checked;return v}
async function persist(){if(!ready)return false;const data=snapshot();if(!store){$('storage-status').textContent='Speicher nicht verfügbar: Daten nur in dieser Sitzung. Jetzt JSON exportieren.';return false}queue=queue.catch(()=>{}).then(()=>writeStore(store,data));try{await queue;$('storage-status').textContent=`Lokal gesichert · ${state.records.length} Records · ungeprüfte Feldevidenz`;$('draft-status').textContent='Entwurf lokal gesichert';return true}catch(e){$('storage-status').textContent='Speichern fehlgeschlagen: Browser-Speicher prüfen und JSON exportieren. Daten bleiben in dieser Sitzung.';$('draft-status').textContent='Nicht dauerhaft gesichert';return false}}
function sourceLink(id){const a=db.manifest.assets.find(x=>x.id===id);return a?`${base}${a.archive.path.split('/').map(encodeURIComponent).join('/')}`:id==='EXT-VZO-INFO'?'https://www.verein-zufriedenheit.com/info.html':`https://github.com/jdistlr/kleines-schaeferrad/blob/main/evidence/manifest.json`}
function sources(ids){return ids.map(id=>`<a href="${esc(sourceLink(id))}" target="_blank" rel="noopener">${esc(id)} ↗</a>`).join(' · ')}
function options(node,values,placeholder){node.innerHTML=(placeholder?`<option value="">${placeholder}</option>`:'')+values.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('')}
function parts(){const q=$('part-search').value.toLowerCase();const alias=q.includes('schetter')?'COMP-PADDLES':q.includes('zwicker')||q.includes('keil')?'COMP-FASTENERS':q.includes('anwell')?'COMP-BEARINGS':null;$('part-list').innerHTML=db.components.filter(c=>!q||`${c.label} ${c.id}`.toLowerCase().includes(q)||c.id===alias).map(c=>`<button data-part="${c.id}" aria-pressed="${c.id===state.selection}">${esc(c.label)}<small>${c.id}</small></button>`).join('')||'<p>Kein Treffer. Begriff kürzen oder „Keil“, „Kumpf“, „Arm“ versuchen.</p>';$('part-list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.part));}
function inspector(){const c=context(state.selection);if(!c.component)return;const recordCount=state.records.filter(r=>r.component_ids.includes(state.selection)&&!r.retracted).length;const ids=[...new Set([...c.component.provenance,...c.claims.flatMap(x=>x.provenance.map(p=>p.source_id))])];const photos=ids.filter(id=>db.manifest.assets.find(a=>a.id===id&&a.filename.match(/\.(jpeg|png)$/i))).slice(0,5);const gap=c.gaps[0];
 $('selection').innerHTML=`<div class="selection-title"><p class="eyebrow">Ausgewähltes Teil</p><h3>${esc(c.component.label)}</h3><p><code>${esc(state.selection)}</code>${state.slot?`<br><small>Hypothesenslot ${esc(state.slot)} · reale Identität offen</small>`:''}</p><p>${esc(c.component.note||'Geometrie und aktuelle Maße bleiben unbestätigt.')}</p><span class="tag">${recordCount} lokale Records · Prüfung offen</span><p><strong>Ist-Maß 2026:</strong> keines freigegeben.</p></div>
 <div class="question"><strong>${gap.id} · ${esc(gap.subject)}</strong><p>${esc(gap.capture)}</p><small>Fertigkriterium: ${esc(gap.acceptance_evidence)}</small><p><a href="#capture">Diese Frage am Teil erfassen ↓</a></p></div>
 <div class="source-images">${photos.map(id=>`<a href="${esc(sourceLink(id))}" target="_blank" rel="noopener"><img src="${esc(sourceLink(id))}" loading="lazy" alt="Quellenbild ${id}"/>${id} ↗</a>`).join('')}</div>
 <details><summary>Claims / Quellen (${c.claims.length})</summary>${c.claims.map(x=>`<article class="claim" id="${x.id}"><strong>${x.id}</strong><span class="tag ${x.evidence_class==='historical-drawing'?'history':''}">${esc(x.evidence_class)}</span><p>${esc(x.predicate)}<span class="claim-value">${esc(typeof x.value==='object'?JSON.stringify(x.value):x.value)} ${esc(x.unit??'· Einheit nicht angegeben')}</span></p><p>${esc(x.scope)} · ${esc(x.note||'Keine aktuelle Maßfreigabe')}</p><small>${x.provenance.map(p=>`${sources([p.source_id])} (${esc(p.region)})`).join('<br>')}</small></article>`).join('')||'<p>Keine eigenen Claims. Quellenbezug siehe Teil und Verbindungen.</p>'}</details>
 <details ${c.conflicts.length?'open':''}><summary>Konflikte (${c.conflicts.length})</summary>${c.conflicts.map(x=>`<p><strong>${x.id}</strong> · ${esc(x.issue)}<br><small>${esc(x.status)} · ${sources(x.sources)}</small></p>`).join('')||'<p>Kein zugeordneter Konflikt. Unbekanntes ist damit nicht geklärt.</p>'}</details>
 <details><summary>Verbindungen / weitere Aufgaben</summary>${c.relations.map(r=>`<p><code>${r.id}</code> ${esc(r.from)} → ${esc(r.to)}<br>${esc(r.type)} · ${sources(r.provenance)}</p>`).join('')}${c.gaps.map(g=>`<p><strong>${g.id}</strong> ${esc(g.subject)} · ${esc(g.priority)}</p>`).join('')}</details>
 <details><summary>Handwerkswissen am Teil</summary>${c.risks.map(r=>`<p><strong>${esc(r.label)}</strong><br>${esc(r.prompt)}</p>`).join('')||'<p>Erfahrung oder Warnsignal mit Teil/Ereignis und Quelle erfassen.</p>'}</details>
 <details><summary>Hypothesenparameter / Nullwerte</summary><p>Alle Renderwerte sind Hypothesen. Unbekannte Passflächen werden nicht geschlossen.</p>${Object.entries(config.parameters).map(([k,v])=>`<p><strong>${esc(k)}</strong>: Anzeige ${esc(v.value??'offen')}; Ist ${esc(v.current_value??'unbekannt')}; Range ${esc(v.range??'unbekannt')}<br><small>${esc(v.note)} · ${esc(v.provenance.join(', '))}</small></p>`).join('')}</details>`;
 $('capture-context').textContent=`${c.component.label} · ${state.selection}${state.slot?' · Slot '+state.slot:''}`;
 const previous={question_id:field('question_id').value,claim_id:field('claim_id').value,relation_id:field('relation_id').value};options(field('question_id'),c.gaps.map(g=>[g.id,`${g.id} · ${g.subject}`]));options(field('claim_id'),c.claims.map(x=>[x.id,`${x.id} · ${x.predicate}`]),'Kein konkreter Claim');options(field('relation_id'),c.relations.map(x=>[x.id,`${x.id} · ${x.type}`]),'Noch nicht zugeordnet');for(const [key,val] of Object.entries(previous))if([...field(key).options].some(o=>o.value===val))field(key).value=val;
}
function select(id,slot=null){if(!db.components.some(c=>c.id===id))return;
 // Do not silently transfer an unfinished record to a different component.
 if(ready&&id!==state.selection&&(field('feature').value.trim()||media.length)){if(!confirm('Der Entwurf gehört zum bisherigen Teil. Auswahl wechseln und den Entwurf verwerfen? Bereits gespeicherte Records bleiben erhalten.'))return;form.reset();media=[];step=1;showStep()}
 state.selection=id;state.slot=slot;inspector();parts();viewer?.select(id);renderMedia();persist();}
function kindFields(){const kind=field('kind').value;form.querySelectorAll('[data-kinds]').forEach(n=>n.hidden=!n.dataset.kinds.split(',').includes(kind));const required=['value','endpoint_a','endpoint_b','tool','uncertainty'];for(const n of required)field(n).required=kind==='measurement'&&!field('unknown').checked;field('quote').required=['expert-narrative','risk'].includes(kind)&&!field('unknown').checked;field('feature').required=!field('unknown').checked;}
function showStep(){form.querySelectorAll('[data-step]').forEach(n=>n.hidden=Number(n.dataset.step)!==step);$('step-indicator').textContent=`Schritt ${step} von 3 · ${['Befund','Kontext & Evidenz','Prüfen & speichern'][step-1]}`;$('step-back').hidden=step===1;$('step-next').hidden=step===3;$('save-record').hidden=step!==3;$('step-next').textContent=step===1?'Weiter zum Kontext':'Weiter zur Prüfung';if(step===3)review();kindFields();}
function stepValid(){const fieldset=form.querySelector(`[data-step="${step}"]`);for(const el of fieldset.querySelectorAll('input,select,textarea')){if(el.closest('[data-kinds]')?.hidden)continue;if(!el.checkValidity()){el.reportValidity();return false}}return true}
function record(){const v=formValues(),c=context(state.selection);return {id:'OBS-'+crypto.randomUUID(),schema:SCHEMA,question_id:v.question_id,event_id:v.event_id,component_ids:[state.selection],slot_id:state.slot,physical_id:v.physical_id||null,relation_ids:v.relation_id?[v.relation_id]:[],partner_ids:v.partners.split(',').map(x=>x.trim()).filter(Boolean),kind:v.kind,feature:v.feature,value:v.kind==='measurement'&&!v.unknown?Number(v.value):null,unit:v.kind==='measurement'?v.unit:null,endpoints:v.kind==='measurement'?{a:v.endpoint_a,b:v.endpoint_b}:null,tool:v.tool||null,uncertainty:v.kind==='measurement'&&!v.unknown?Number(v.uncertainty):null,side:v.side,state:v.state,person:v.person,timestamp:new Date().toISOString(),media:[...media,...(v.media_reference?[{id:'REF-'+crypto.randomUUID(),name:v.media_reference,role:v.media_role,external:true}]:[])],quote:v.quote||null,interpretation:v.interpretation||null,confidence:v.confidence,unknown:!!v.unknown,variant:v.kind==='identification'?v.variant:null,orientation:v.orientation||null,storage_location:v.storage_location||null,claim_ids:v.claim_id?[v.claim_id]:[],conflict_ids:c.conflicts.map(x=>x.id),effect:v.effect,review_status:'unreviewed-local',craft:v.kind==='risk'?{topic:v.risk_topic,trigger:v.trigger,mechanism:v.mechanism,expected_behaviour:v.expected_behaviour,failure_consequence:v.failure_consequence,warning_sign:v.warning_sign,mitigation:v.mitigation,source_person:v.person,alternate_account:v.alternate_account}:null};}
function review(){const r=record();$('review').innerHTML=`<p><strong>${esc(labels[r.kind])}</strong> · ${esc(r.question_id)} · ${esc(r.component_ids[0])}</p><p>${esc(r.feature||'Weiß ich nicht / noch nicht zugänglich')}</p>${r.kind==='measurement'&&!r.unknown?`<p>${r.value} ${esc(r.unit)} ± ${r.uncertainty}; ${esc(r.endpoints.a)} → ${esc(r.endpoints.b)}; ${esc(r.tool)}</p>`:''}<p>${esc(r.person)} · ${esc(r.event_id)} · ${esc(r.side)} · ${esc(r.state)}</p><p>${r.media.length} Medienreferenzen · ${esc(r.effect)}: ${esc(r.claim_ids.join(', ')||'kein Claim ausgewählt')}</p><p>Adressiert: ${esc(r.conflict_ids.join(', ')||'kein Konflikt')} / ${esc(r.question_id)}. Neue Evidenz wartet auf Prüfung.</p>`;}
function renderMedia(){$('media-list').innerHTML=media.map((m,i)=>`<div><img class="media-thumb" src="${esc(m.data_url)}" alt="${esc(m.name)}"/><small>${esc(m.name)} · ${esc(m.role)}</small> <button type="button" data-remove-media="${i}">Foto entfernen</button></div>`).join('');$('media-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{media.splice(Number(b.dataset.removeMedia),1);renderMedia();persist()})}
function records(){$('record-count').textContent=state.records.filter(r=>!r.retracted).length;$('record-list').innerHTML=state.records.map(r=>`<article class="record"><strong>${esc(labels[r.kind])} · ${esc(r.question_id)}</strong><p>${esc(r.feature||'Unbekannt / nicht zugänglich')}</p><small>${esc(r.component_ids.join(', '))} · ${esc(r.person)} · ${esc(r.timestamp)} · ${r.retracted?'zurückgezogen':'ungeprüft lokal'}</small><p>${esc(r.id)} · ${r.media.length} Medien</p><details><summary>Record vollständig ansehen</summary><pre>${esc(JSON.stringify({...r,media:r.media.map(m=>({...m,data_url:m.data_url?'[Bildbytes im Export]':undefined}))},null,2))}</pre>${r.media.filter(m=>m.data_url).map(m=>`<img class="media-thumb" src="${esc(m.data_url)}" alt="${esc(m.name)}"/>`).join('')}</details>${!r.retracted?`<button data-retract="${esc(r.id)}">Record zurückziehen</button>`:''}</article>`).join('')||'<p>Noch kein Record. Wähle ein Teil und erfasse die erste Beobachtung.</p>';$('record-list').querySelectorAll('[data-retract]').forEach(b=>b.onclick=()=>{const r=state.records.find(x=>x.id===b.dataset.retract);r.retracted=true;r.retracted_at=new Date().toISOString();records();inspector();persist()});}
function restoreDraft(d){if(!d?.values)return;for(const [name,value] of Object.entries(d.values)){const el=field(name);if(!el||el.type==='file')continue;if(el.type==='checkbox')el.checked=!!value;else el.value=value}media=Array.isArray(d.media)?d.media:[];step=[1,2,3].includes(d.step)?d.step:1;showStep();renderMedia();$('draft-status').textContent='Unterbrochene Aufgabe wiederhergestellt';}
$('part-search').oninput=parts;
$('capture-actions').querySelectorAll('button').forEach(b=>b.onclick=()=>{field('kind').value=b.dataset.kind;step=1;showStep();persist();$('capture-form').scrollIntoView({behavior:'smooth',block:'start'})});
$('step-next').onclick=()=>{if(!stepValid())return;step++;showStep();persist();$('step-indicator').scrollIntoView({block:'nearest'})};$('step-back').onclick=()=>{step--;showStep();persist()};
form.oninput=()=>{kindFields();if(step===3)review();persist()};form.onchange=()=>{kindFields();if(step===3)review();persist()};
form.onsubmit=async e=>{e.preventDefault();$('form-error').textContent='';try{if(!stepValid())return;const r=record();if(['supports','challenges'].includes(r.effect)&&!r.claim_ids.length)throw Error('Für Stützen/Widersprechen bitte einen Claim wählen.');validateRecord(r);state.records.push(r);const saved=await persist();records();inspector();form.reset();media=[];step=1;showStep();renderMedia();await persist();$('draft-status').textContent=saved?'Record lokal gesichert · neue Erfassung bereit':'Record nur in dieser Sitzung · jetzt exportieren';$('records').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){$('form-error').textContent=err.message}};
$('media-input').onchange=async e=>{const files=[...e.target.files];$('media-status').textContent='Foto wird gesichert …';try{for(const f of files){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3*1024*1024)throw Error(`${f.name}: nur JPEG/PNG/WebP bis 3 MB. Größere Originale separat sichern und referenzieren.`);const data_url=await new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(rd.result);rd.onerror=reject;rd.readAsDataURL(f)});const hash=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());media.push({id:'MEDIA-'+crypto.randomUUID(),name:f.name,type:f.type,bytes:f.size,sha256:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''),role:field('media_role').value,data_url});}renderMedia();await persist();$('media-status').textContent=`${media.length} Foto(s) im Entwurf; Originalbytes im Export.`}catch(err){$('media-status').textContent=err.message}e.target.value=''};
$('export').onclick=()=>{const payload={...snapshot(),exported_at:new Date().toISOString(),baseline:'dd0cd480a4f509a1137ca19a7f9075a8aba0c30a'},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`KS-Feldprotokoll-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('Datei ist größer als 100 MB.');const payload=JSON.parse(await f.text());const merged=mergeImport(state.records,payload);state.records=merged;if(!field('feature').value.trim()&&!media.length&&payload.draft&&db.components.some(c=>c.id===payload.draft.component_id)){state.selection=payload.draft.component_id;state.slot=payload.draft.slot;inspector();parts();restoreDraft(payload.draft);viewer?.select(state.selection)}records();inspector();await persist();$('storage-status').textContent=`${merged.length} Records nach Import. Duplikate unverändert; Baseline bleibt bestehen.`}catch(err){$('storage-status').textContent=`Import abgebrochen: ${err.message}`}e.target.value=''};
(async()=>{try{store=await openStore();const saved=await readStore(store);if(saved?.schema===SCHEMA){mergeImport([],saved);state=saved}}catch(e){$('storage-status').textContent='Lokaler Speicher nicht verfügbar. Export verwenden.'}if(!db.components.some(c=>c.id===state.selection))state.selection='COMP-SHAFT';inspector();parts();records();restoreDraft(state.draft);showStep();const savedViewer=structuredClone(state.viewer||{});try{viewer=createViewer(base,select,id=>{select(id);$('capture').scrollIntoView({behavior:'smooth'})},patch=>{state.viewer={...state.viewer,...patch};persist()});viewer.restore(savedViewer);viewer.select(state.selection)}catch(e){$('render-status').textContent='3D nicht verfügbar. Alle Aufgaben bleiben über Teilfinder, Quellen und Zeichnungen erreichbar.';console.warn('WebGL unavailable',e)}ready=true;await persist();})();
