import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import {makeModel,matchesFamily,disposeModel,views} from './geometry.mjs';
const viewLabels={gesamt:'Gesamt',land:'Seite A',wasser:'Seite B',welle:'Welle / Arme',kranz:'Kranz',kumpf:'Kumpf',schaufeln:'Schaufeln'};
export function createViewer(base,onSelect,onQuestion,onSettings){
 const $=id=>document.getElementById(id),host=$('canvas-host');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Hypothesenmodell; alternativ Teilfinder und Standardansichten verwenden');
 const scene=new T.Scene(),camera=new T.OrthographicCamera(-4,4,3,-3,.1,100);camera.up.set(0,0,1);scene.add(new T.HemisphereLight(0xffffff,0x69735d,2.5));const light=new T.DirectionalLight(0xffffff,2);light.position.set(3,-6,8);scene.add(light);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enabled=false;controls.enableDamping=false;controls.enablePan=true;controls.minZoom=.5;controls.maxZoom=6;
 let model,variant='A',exploded=false,cut=false,view='gesamt',selection='COMP-SHAFT',scan=null,scanPromise=null,historical;
 const plane=new T.Plane(new T.Vector3(0,-1,0),0); const ray=new T.Raycaster(),mouse=new T.Vector2();
 const pinData=[{family:'COMP-SHAFT',text:'? 02',point:[0,0,0]},{family:'COMP-KRUEMMLINGE',text:'↔ 03',point:[-.65,-1.6,1.2]},{family:'COMP-KUEMPFE',text:'? 04',point:[-.65,1.9,.5]},{family:'COMP-BEARINGS',text:'↔ 06',point:[1.65,0,-.3]}];
 const pinEls=pinData.map(p=>{const b=document.createElement('button');b.className='pin';b.textContent=p.text;b.setAttribute('aria-label',`Frage / Messstelle ${p.family}`);b.onclick=()=>onQuestion(p.family);$('pins').append(b);return b});
 function build(){if(model){scene.remove(model);disposeModel(model)}if(historical){scene.remove(historical);disposeModel(historical)}model=makeModel(variant,exploded?1:0);scene.add(model);historical=new T.Group();for(const mesh of model.children){if(mesh.userData.stationary)continue;const e=new T.LineSegments(new T.EdgesGeometry(mesh.geometry,25),new T.LineBasicMaterial({color:0x322e25,transparent:true,opacity:.8}));e.position.copy(mesh.position);e.rotation.copy(mesh.rotation);historical.add(e)}scene.add(historical);apply();}
 function apply(){for(const mesh of model.children){mesh.visible=$('layer-model').checked&&(!mesh.userData.stationary||$('layer-stationary').checked);mesh.material.clippingPlanes=cut?[plane]:[];mesh.material.color.setHex(matchesFamily(mesh,selection)?0xd79c34:mesh.userData.stationary?0x738178:mesh.userData.family==='COMP-KUEMPFE'?0xb68a44:0x377d79);mesh.material.opacity=matchesFamily(mesh,selection)?.83:mesh.userData.stationary?.25:.5;for(const e of mesh.children)e.material.clippingPlanes=cut?[plane]:[];}historical.visible=$('layer-historical').checked;for(const e of historical.children)e.material.clippingPlanes=cut?[plane]:[];if(scan)scan.visible=$('layer-scan').checked;$('pins').hidden=!$('layer-questions').checked;render()}
 function render(){renderer.render(scene,camera);const rect=host.getBoundingClientRect();pinData.forEach((p,i)=>{const v=new T.Vector3(...p.point).project(camera);pinEls[i].style.left=`${(v.x+1)/2*rect.width}px`;pinEls[i].style.top=`${(1-v.y)/2*rect.height}px`;pinEls[i].hidden=v.z>1||Math.abs(v.x)>.93||Math.abs(v.y)>.9;});}
 function standard(name){view=name;let target=new T.Vector3(),zoom=1;if(name==='kumpf'){target.set(-.6,0,2.25);zoom=3}else if(name==='welle'){zoom=1.35}controls.target.copy(target);camera.position.copy(target).add(new T.Vector3(...views[name]));camera.zoom=zoom;camera.lookAt(target);camera.updateProjectionMatrix();controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));$('view-label').textContent=`${name} · Hypothese ${variant}${exploded?' · Explode':''}${cut?' · offener Halbschnitt':''}`;apply();onSettings({view,variant,exploded,cut})}
 function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height,false);const aspect=r.width/r.height;camera.left=-3.3*aspect;camera.right=3.3*aspect;camera.top=3.3;camera.bottom=-3.3;camera.updateProjectionMatrix();render()}
 controls.addEventListener('change',render);new ResizeObserver(resize).observe(host);
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=host.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(model.children,false).find(h=>h.object.visible&&(!cut||h.point.y<=0));if(hit)onSelect(hit.object.userData.family,hit.object.userData.id)});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>standard(b.dataset.view));$('reset').onclick=()=>{controls.enabled=false;$('orbit').setAttribute('aria-pressed','false');$('orbit').textContent='Modell bewegen: aus';exploded=false;cut=false;$('explode').setAttribute('aria-pressed','false');$('explode').textContent='Auseinanderziehen: aus';$('cut').setAttribute('aria-pressed','false');$('cut').textContent='Halbschnitt: aus';build();standard('gesamt')};
 $('orbit').onclick=()=>{controls.enabled=!controls.enabled;$('orbit').setAttribute('aria-pressed',String(controls.enabled));$('orbit').textContent=`Modell bewegen: ${controls.enabled?'an':'aus'}`;renderer.domElement.style.touchAction=controls.enabled?'none':'pan-y'};renderer.domElement.style.touchAction='pan-y';
 $('explode').onclick=()=>{exploded=!exploded;$('explode').setAttribute('aria-pressed',String(exploded));$('explode').textContent=`Auseinanderziehen: ${exploded?'an':'aus'}`;build();standard(view)};
 $('cut').onclick=()=>{cut=!cut;$('cut').setAttribute('aria-pressed',String(cut));$('cut').textContent=`Halbschnitt: ${cut?'an':'aus'}`;standard(view)};
 $('variant').onclick=()=>{variant=variant==='A'?'B':'A';$('variant').setAttribute('aria-pressed',String(variant==='B'));$('variant').textContent=`Kumpf-Variante ${variant} · ${variant==='A'?24:22} mm`;build();standard(view)};
 for(const id of ['model','stationary','historical','questions'])$('layer-'+id).onchange=apply;
 $('layer-scan').onchange=async()=>{if($('layer-scan').checked&&!scan){$('scan-status').textContent='GLB wird geladen …';try{scanPromise ||= new GLTFLoader().loadAsync(base+'evidence/raw/Scaniverse%202026-10-07%20173556.glb');const gltf=await scanPromise;scan=gltf.scene;scan.traverse(o=>{if(o.isMesh){o.material=new T.MeshBasicMaterial({color:0x796cad,wireframe:true,transparent:true,opacity:.25});o.userData.status='unregistered-scan-fragment'}});scene.add(scan);transformScan();$('scan-status').textContent='3D-Scan geladen. Achsenkorrektur, mechanischer Bezug und Maßstab sind noch offen.'}catch(e){scanPromise=null;$('scan-status').textContent='Scan konnte nicht geladen werden. Verbindung prüfen und erneut einschalten.';$('layer-scan').checked=false}}apply()};
 function transformScan(){const vals={};for(const key of ['x','y','z','scale','rx','ry','rz'])vals[key]=Number($('scan-'+key).value);if(!Object.values(vals).every(Number.isFinite)||vals.scale<=0)return;scan?.position.set(vals.x,vals.y,vals.z);scan?.scale.setScalar(vals.scale);scan?.rotation.set(vals.rx*Math.PI/180,vals.ry*Math.PI/180,vals.rz*Math.PI/180);onSettings({scan_transform:vals});render()}
 for(const key of ['x','y','z','scale','rx','ry','rz'])$('scan-'+key).oninput=transformScan;
 $('scan-reset').onclick=()=>{for(const key of ['x','y','z','scale','rx','ry','rz'])$('scan-'+key).value=key==='scale'?'1':'0';transformScan()};
 build();standard('gesamt');resize();$('render-status').textContent='Teil antippen · freie Bewegung erst mit „Modell bewegen“';
 return {select(id){selection=id;apply()},restore(s){if(s?.scan_transform)for(const [k,v] of Object.entries(s.scan_transform))if($('scan-'+k))$('scan-'+k).value=v;variant=s?.variant==='B'?'B':'A';exploded=!!s?.exploded;cut=!!s?.cut;$('variant').textContent=`Variante ${variant} · ${variant==='A'?24:22} mm`;$('variant').setAttribute('aria-pressed',String(variant==='B'));$('explode').textContent=`Explode: ${exploded?'an':'aus'}`;$('explode').setAttribute('aria-pressed',String(exploded));$('cut').textContent=`Halbschnitt: ${cut?'an':'aus'}`;$('cut').setAttribute('aria-pressed',String(cut));build();standard(views[s?.view]?s.view:'gesamt')}};
}
